FROM debian:11

RUN apt-get update && apt-get upgrade && \
	apt-get install -y mariadb-server && \
	apt-get clean && rm -fr /var/lib/apt/lists/*

COPY conf/my.cnf /etc/mysql/my.cnf
COPY tools/entrypoint.sh /entrypoint.sh

RUN chmod +x /entrypoint.sh

EXPOSE 3306

ENTRYPOINT [ "/entrypoint.sh" ]
CMD ["mysqld"]
