FROM debian:11

RUN apt-get update && apt-get upgrade && \
	apt-get install -y mariadb-server && \
	apt-get clean && rm -fr /var/lib/apt/lists/*

COPY conf/my.cnf /etc/mysql/my.cnf
COPY tools/init-db.sh /docker-entrypoint-initdb.d/

RUN chmod +x /docker-entrypoint-initdb.d/init-db.sh

EXPOSE 3306

CMD ["mysqld"]
