FROM debian:11

RUN apt-get update && \
	apt-get install -y php8.2-fpm php8.2-mysql curl && \
	apt-get clean && \
	rm -rf /var/lib/apt/lists/*

WORKDIR /var/www/html
COPY . /var/www/html/

EXPOSE 9000

CMD [ "php-fpm8.2", "-F" ]